const { generateWithGemini } = require("../../shared/gemini");
const { sanitizeText } = require("../../shared/sanitize");

const swahiliHints = {
  recommendation: "Nimepata safari bora kulingana na bei, muda, na uaminifu wa route.",
  pricing: "Ninaweza kukushauri muda wa bei nafuu kabla hujahifadhi.",
  delay: "Ninaweza kukupa tahadhari ya ucheleweshaji kwa route uliyochagua.",
  fraud: "Muamala huu una alama zisizo za kawaida na unahitaji ukaguzi."
};

const englishHints = {
  recommendation: "I found the best trip based on price, time, and reliability.",
  pricing: "I can suggest a cheaper departure window before booking.",
  delay: "I can flag delay risk for your selected route.",
  fraud: "This transaction shows unusual behavior and needs review."
};

function inferIntent(text) {
  const lower = (text || "").toLowerCase();

  if (lower.includes("cheap") || lower.includes("bei")) {
    return "pricing";
  }
  if (lower.includes("delay") || lower.includes("uchelewesh")) {
    return "delay";
  }
  if (lower.includes("fraud") || lower.includes("suspicious")) {
    return "fraud";
  }
  return "recommendation";
}

async function respondToPrompt({ text, language = "en" }) {
  const userText = sanitizeText(text, 500);
  const intent = inferIntent(userText);
  const hints = language === "sw" ? swahiliHints : englishHints;
  const fallbackMessage = hints[intent] || hints.recommendation;

  if (!userText) {
    return {
      intent,
      message: fallbackMessage,
      source: "fallback",
      modelUsed: null
    };
  }

  const prompt = [
    "You are Safari Connect AI agent for transport booking decisions.",
    `Language: ${language}.`,
    `Detected intent: ${intent}.`,
    "Respond in 1-2 concise sentences and provide practical guidance.",
    "Do not invent live prices, schedules, or seat availability.",
    "If data is missing, ask for route, date/time, and budget in one short question.",
    "Use cautious wording: based on the provided input.",
    `User message: ${userText}`
  ].join("\n");

  const result = await generateWithGemini({ prompt });

  return {
    intent,
    message: result.text || fallbackMessage,
    source: result.source,
    modelUsed: result.modelUsed,
    disclaimer:
      result.source === "fallback"
        ? "Response generated from deterministic fallback guidance."
        : "Response generated by Gemini from provided context."
  };
}

module.exports = {
  respondToPrompt
};
